### ISSUE TITLE
how to fix "file does not exist and no rule available"?

### ISSUE THREAD

**Issue by luckypoem** [seagreen/housejeffries#2]
hi.

root@AR:/usr/local/housejeffries-site# /usr/local/housejeffries-site/.stack-work/install/i386-linux/nightly-2016-09-09/8.0.1/bin/main build
Error when running Shake build system:
- build
  Error, file does not exist and no rule available:
  build
  CallStack (from HasCallStack):
  error, called at src/Development/Shake/Rules/File.hs:103:58 in shake-0.15.10-GcLMYwHJl6F2fOZ4KrIiXZ:Development.Shake.Rules.File

root@AR:/usr/local/housejeffries-site# 

thank you

**Comment by seagreen** [comment]
I just switched over to the foward-defined version of Shake: https://github.com/seagreen/housejeffries/blob/master/Main.hs#L72 ([Development.Shake.Forward](https://hackage.haskell.org/package/shake-0.15.11/docs/Development-Shake-Forward.html)). This will make problems like yours not occur because we don't have to both figure out what to build, write our rules, and hope they match up. Instead we just look at the source files and then do things based on them in one step.

**Comment by luckypoem** [comment]
hi.

root@localhost:/usr/local/housejeffries-site# stack build
Executable named nix-shell not found on path: ["/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games","/root/racket-6.0.1/bin","/root/.stack/programs/x86_64-linux/ghc-8.0.1/bin","/root/.cabal/bin","/usr/local/rvm/gems/ruby-2.3.0/bin","/usr/local/rvm/rubies/ruby-2.3.0/bin","/usr/local/rvm/bin","/usr/local/piecrust-site/bin","/usr/local/go/bin"]
root@localhost:/usr/local/housejeffries-site#

how to fix it?

**Comment by seagreen** [comment]
The code assumes you're using [NixOS](https://nixos.org/). Since you're not you can go to [this line](https://github.com/seagreen/housejeffries/blob/master/stack.yaml#L8) and change `enable: true` to `enable: false` and that will fix it.

That still won't get you all the way to building the site though. As you can see the code is [pretty litered](https://github.com/seagreen/housejeffries/blob/master/Main.hs#L98) with references to local files that aren't included in this repo. This is so that each page gets its own history independent of the rest of the site, for instance the home page from the previous link lives in its own repo here: https://github.com/housejeffries-pages/1

I'll push up a few more comments to make the code more clear today, and let me know if you have any other questions.

**Comment by seagreen** [comment]
I updated the README, it should be less confusing now.

**Comment by luckypoem** [comment]
this time,
root@localhost:/usr/local/housejeffries-site# stack build
it shows:
...
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main ...
housejeffries-0.0.1.0: copy/register
Installing library in
/usr/local/housejeffries-site/.stack-work/install/x86_64-linux/lts-7.2/8.0.1/lib/x86_64-linux-ghc-8.0.1/housejeffries-0.0.1.0-3LeNhbqhbj2AF6stScBHaL
Installing executable(s) in
/usr/local/housejeffries-site/.stack-work/install/x86_64-linux/lts-7.2/8.0.1/bin
Registering housejeffries-0.0.1.0...
Completed 92 action(s).
root@localhost:/usr/local/housejeffries-site#

then,
root@localhost:/usr/local/housejeffries-site# .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main build
main: Error when running Shake build system:
* getDirectoryDirs /home/traveller/code/mine/hjpages
/home/traveller/code/mine/hjpages: getDirectoryContents: does not exist (No such file or directory)

root@localhost:/usr/local/housejeffries-site#

how to fix it?

**Comment by luckypoem** [comment]
root@localhost:/usr/local/housejeffries-site# .stack-work/install/x86_64-linux/lts-7.2/8.0.1/bin/main build
main: Error when running Shake build system:
* getDirectoryDirs /home/traveller/code/mine/hjpages
/home/traveller/code/mine/hjpages: getDirectoryContents: does not exist (No such file or directory)

root@localhost:/usr/local/housejeffries-site#

**Comment by seagreen** [comment]
Make sure you're following the instructions in [the README](https://github.com/seagreen/housejeffries), and understand why they exist. What do you have the `pageDir` set to? This is the location the build system will go to find each page (pages are each directories themselves, with `page.md` and `meta.json` files).

**Comment by luckypoem** [comment]
it's still not ok.

i created pages dir in src:
root@localhost:/usr/local/housejeffries-site/src# ls
css  haskell  pages  resources  templates
root@localhost:/usr/local/housejeffries-site/src# 
root@localhost:/usr/local/housejeffries-site/src# ls pages
2  3  4  5  6  7  page.md
root@localhost:/usr/local/housejeffries-site/src#
root@localhost:/usr/local/housejeffries-site/src# cd ..
root@localhost:/usr/local/housejeffries-site# ls
_build  housejeffries.cabal  Main.hs  MIT-LICENSE.txt  README.md  run  shell.nix  src  stack.yaml
root@localhost:/usr/local/housejeffries-site# 
root@localhost:/usr/local/housejeffries-site# .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main build
main: Error when running Shake build system:
* getDirectoryDirs /home/traveller/code/mine/hjpages
/home/traveller/code/mine/hjpages: getDirectoryContents: does not exist (No such file or directory)
root@localhost:/usr/local/housejeffries-site# 

why still encounter error??(http://104.223.21.28:2358/Main.hs,pls check my amended Main.hs,
is  my amended Main.hs file not correct?

**Comment by seagreen** [comment]
Your `Main.hs` looks good to me. Since the error mentions that `/home/traveller/code/mine/hjpages` can't be found, there still must be a reference to it in the code you're running. Try deleting the current executable and recompiling to make sure your executable matches the current source code.

**Comment by luckypoem** [comment]
hi.

still not ok.
root@localhost:/usr/local/housejeffries-site# rm .stack-work/install/x86_64-linux/lts-7.2/8.0.1/bin/main
root@localhost:/usr/local/housejeffries-site# rm .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main 
root@localhost:/usr/local/housejeffries-site# ls
_build               Main.hs          README.md  shell.nix  stack.yaml
housejeffries.cabal  MIT-LICENSE.txt  run        src
root@localhost:/usr/local/housejeffries-site# stack build
housejeffries-0.0.1.0: unregistering (local file changes: Main.hs)
housejeffries-0.0.1.0: configure (lib + exe)
Configuring housejeffries-0.0.1.0...
housejeffries-0.0.1.0: build (lib + exe)
Preprocessing library housejeffries-0.0.1.0...
Preprocessing executable 'main' for housejeffries-0.0.1.0...
[1 of 1] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main ...
housejeffries-0.0.1.0: copy/register
Installing library in
/usr/local/housejeffries-site/.stack-work/install/x86_64-linux/lts-7.2/8.0.1/lib/x86_64-linux-ghc-8.0.1/housejeffries-0.0.1.0-3LeNhbqhbj2AF6stScBHaL
Installing executable(s) in
/usr/local/housejeffries-site/.stack-work/install/x86_64-linux/lts-7.2/8.0.1/bin
Registering housejeffries-0.0.1.0...
root@localhost:/usr/local/housejeffries-site# ls
_build  housejeffries.cabal  Main.hs  MIT-LICENSE.txt  README.md  run  shell.nix  src  stack.yaml
root@localhost:/usr/local/housejeffries-site# .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/main/main build
main: Error when running Shake build system:
* Top-level action/want
/usr/local/housejeffries-site/_site/index.html: openFile: does not exist (No such file or directory)

root@localhost:/usr/local/housejeffries-site#

how to fix it?tks

**Comment by luckypoem** [comment]
root@localhost:/usr/local/housejeffries-site# ls
_build  housejeffries.cabal  Main.hs  MIT-LICENSE.txt  README.md  run  shell.nix  src  stack.yaml
root@localhost:/usr/local/housejeffries-site# ls _site
ls: cannot access _site: No such file or directory
root@localhost:/usr/local/housejeffries-site#

_site isn't generated at all

**Comment by seagreen** [comment]
Try creating `_site` manually.

**Comment by seagreen** [comment]
I've switched to Shake's forward defined build system, `Development.Shake.Forward`, so a lot of these hard-to-debug problems won't show up any more. Let me know if you have more questions.
